'use strict'
const QUIZ = [
           {
            id: "js-question1",
            question: "How are you (informal)?",
            number: 1,
            answers: [
            "¿Como estas?",
             "¿Cómo estás?",
             "¿Cómo eres?",
             "¿Qué cómo?"],
            answer: 1,
            
        },

        {
            id: "js-question2",
            question: "What are you doing (formal)?",
            number: 2,
            answers: [
                "¿Qué haga?",
                "¿Qué haces?",
                "¿Qué haciendo?",
                "¿Qué está haciendo?"],
            answer: 3,
        },
        
        {
            id: "js-question3",
            question: "What have you done (informal)?",
            number: 3,
            answers: [
                "¿Qué has hecho?",
                "¿Qué ha hecho?",
                "¿Qué has hace?",
                "¿Qué habían hecho?"],
            answer: 0,
        },
        
        {
            id: "js-question4",
            question: "What were you cooking (informal)?",
            number: 4,
            answers: [
                "¿Qué estás cocinando?",
                "¿Qué cocinas?",
                "¿Qué cocinaba?",
                "¿Qué cocinabas?"],
            answer: 3,
        },
        
        {
            id: "js-question5",
            question: "When will you visit (informal)?",
            number: 5,
            answers: [
                "¿Cuándo visitaré?",
                "¿Cuándo visitará?",
                "¿Cuándo visitarás?",
                "¿Cuándo vas a venir?"],
            answer: 2,
        },

]

//QUESTIONS returns an array of all questions from the QUIZ data model
let questions = QUIZ.map(item => {        
    return item.question;
});
// console.log(`questions is ${questions}`);

//ANSWERS returns an array of objects
let answers = QUIZ.map(item =>{ 
    return item.options 
});
// console.log(`answers is ${answers}`);

//NUMBER is INDEX used for functions: 1) returnQuestionAtI() 2) returnAnswers(number)
let number = 0;

//NUM is used to determine the question number user is on
let num = 1;


    function generateQuestionElement(quiz) {
//returns an html element with the QUESTION object property inserted as content
// console.log(`generateQuestionElement returns: <h4>${quiz.question}</h4>`);
        return `<h4>${quiz.question}</h4>`
    }
    
    function generateAnswer(answers) {
        const answerSet = answers.map((options) => 
        generateAnswerElementString())

    }

    function generateAnswerElementString() {
        return `<li>${quiz.options["option1"]} </li>`;
    }

    function generateQuestionElementString(questions) {
//declare a variable to store an array created by .map(): for each QUIZ question, create an element using generateQuestionElement (line 112)
        const question = questions.map((question) => 
        generateQuestionElement(question));    
// console.log(`question is ${question}`)

//join the array into a string and return that string, with each item separated by a comma
        return question.join("");
    }

    function renderQuestionSet() {
//declare a variable to store a QUESTION element string generated by generateQuestionElementString (line 118)
        const questionString = 
//pass that QUESTION string element (generated from the QUIZ store) as the argument
        generateQuestionElementString(QUIZ);
//insert that ELEMENT into the DOM at <h4>
        $("h4").html(questionString);

// console.log(`questionString is ${questionString}`)
// console.log(`renderQuestionSet returns:`)
        // return questionString;
    }
    function generateAnswerElement(quiz) {
        let answers = quiz.options;
        
console.log(`answers is ${answers}`)

        let answerSet = Object.values(answers);
        answerSet.join("")
console.log(`answerSet is: ${answerSet}`)
        return answerSet.join("");
    }


    
  // generateQuestionElement()
    function startQuiz() {

    }

    function showQuestionNumber() {

    }
    function handleNextButton() {

    }
    function handleStartButton() {

    }

  
  

    function showFeedback(answer) {
        // let correctAnswer = this.options["option2"];
        // if(answer === correctAnswer) {        
        //     return `Great! "${correctAnswer}" is correct;`
        // } else {
        //     return `Oops! "${correctAnswer}" is the correct answer.`
        // }
    }
//returnQuestionAtI() returns a question at the specified index, i.e., `NUMBER` 
    
    
    function restartQuiz() {
        
    };
    

// returnQuestionAtI(0);
function handleQuiz() {

    
}

             
$(handleQuiz);

